name: Create branch from external dispatch

on:
  - repository_dispatch

jobs:
  create_branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - uses: peterjgrainger/action-create-branch@v1.0.0
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     branch: ${{ github.event.client_payload.version }}
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: tag hub-tests with crowdsec tag
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo_token: ${{ secrets.REPO_ACCESS_TOKEN }}
          tag: ${{ steps.get_version.outputs.VERSION }}
