name: Create branch from external dispatch

on:
  repository_dispatch:
    types: ['create_tag']

jobs:
  create_branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: tag hub-tests with crowdsec tag
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.REPO_ACCESS_TOKEN }}
          tag: ${{ github.event.client_payload.version }}
