name: Trigger hub CI

on: 
  push:
    branches:
    - master

jobs:
  trigger_hub_ci:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: crowdsecurity/hub
          event-type: my-event
