name: Print on external push

on:
  repository_dispatch:
    types: ['create_tag']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set env
        run: echo ::set-env name=TAG::$(echo "${{ github.event.client_payload.ref }}" | cut -d "/" -f3)
      - name: Run a one-line script
        uses: tvdias/github-tagger@v0.0.1
        with:
          tag: "${{ env.TAG }}"
          repo-token: "${{ secrets.GITHUB_TOKEN }}"